set_property PACKAGE_PIN E8 [get_ports {led[3]}]
set_property PACKAGE_PIN F8 [get_ports {led[2]}]
set_property PACKAGE_PIN A7 [get_ports {led[1]}]
set_property PACKAGE_PIN A6 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property PACKAGE_PIN V9 [get_ports rst_n]
set_property PACKAGE_PIN AE5 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]

create_clock -period 5.000 -name clk -waveform {0.000 2.500} [get_ports clk]
