set_property PACKAGE_PIN A6 [get_ports {led[0]}]
set_property PACKAGE_PIN A7 [get_ports {led[1]}]
set_property PACKAGE_PIN F8 [get_ports {led[2]}]
set_property PACKAGE_PIN E8 [get_ports {led[3]}]
set_property PACKAGE_PIN V9 [get_ports {sw[0]}]
set_property PACKAGE_PIN U9 [get_ports {sw[1]}]
set_property PACKAGE_PIN T8 [get_ports {sw[2]}]
set_property PACKAGE_PIN R8 [get_ports {sw[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[0]}]
